### ISSUE TITLE
Requesting for chapter Readme file and course ppt

### ISSUE THREAD

**Issue by sauravsolanki** [K8sAcademy/Fundamentals-HandsOn#2]
Hi Barrette ,

Thank you for this awesome session on kubernetes. You have covered almost everything that we need to build the knowledge base and skyrocket from here.

We might need content in brief for revision so, Can you please share the cheatsheet, readme file and presentation.

**Comment by guybarrette** [comment]
Sorry, those documents will not be shared.

**Comment by sauravsolanki** [comment]
ok Barrette. Thank you for your contribution in open source community.
